name: Java CI with Gradle

on:
    push:
        branches: [ master , develop ]
    pull_request:
        branches: [ master, develop ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: set up JDK 15.0.0-ea
              uses: actions/setup-java@v3
              with:
                  java-version: '20'
                  distribution: 'temurin'
                  cache: gradle
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run:  ./gradlew koverVerifyDebug koverXmlReportDebug
            - name: Upload coverage reports
              uses: codecov/codecov-action@v2
              with:
                  files: build/reports/kover/report.xml